# Generated by Django 4.2.7 on 2023-11-02 02:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RangPlayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=100)),
                ("teams", models.CharField(blank=True, default="", max_length=100)),
                ("kills", models.FloatField(blank=True, default=0)),
            ],
        ),
    ]
