# Generated by Django 4.2.7 on 2023-11-02 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rangplayer',
            name='dead',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='rangplayer',
            name='kd',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
