# Generated by Django 4.2.7 on 2023-11-02 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rangplayer_dead_rangplayer_kd'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='rangplayer',
            name='teams',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.teams'),
        ),
    ]
