# Generated by Django 4.2.7 on 2023-11-02 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_teams_alter_rangplayer_teams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rangplayer',
            name='teams',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
