# Generated by Django 4.2.7 on 2023-11-02 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_rangplayer_teams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rangplayer',
            name='teams',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.teams'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
