# Generated by Django 4.2.5 on 2023-11-23 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_rangplayer_teams_alter_teams_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterDota2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DotaHeroes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('role', models.CharField(blank=True, default='', max_length=100)),
                ('attacktype', models.CharField(blank=True, default='', max_length=100)),
                ('tooltipe', models.CharField(blank=True, default='', max_length=100)),
                ('images', models.CharField(blank=True, default='', max_length=100)),
                ('type', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TeamDota2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerDota2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('steamid', models.CharField(blank=True, default='', max_length=100)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.teamdota2')),
            ],
        ),
        migrations.CreateModel(
            name='GameDota2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold', models.IntegerField()),
                ('kills', models.IntegerField()),
                ('dead', models.IntegerField()),
                ('assists', models.IntegerField()),
                ('role', models.CharField(blank=True, default='', max_length=100)),
                ('characters', models.ManyToManyField(to='api.characterdota2')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.playerdota2')),
            ],
        ),
    ]
