# Generated by Django 4.2.5 on 2023-11-23 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_characterdota2_dotaheroes_teamdota2_playerdota2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamedota2',
            name='hero_played',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.dotaheroes'),
        ),
    ]
