# Generated by Django 4.2.5 on 2023-11-23 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_gamedota2_hero_played'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamedota2',
            name='player',
        ),
        migrations.AddField(
            model_name='gamedota2',
            name='player_1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='player_1', to='api.playerdota2'),
        ),
        migrations.AddField(
            model_name='gamedota2',
            name='player_10',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='player_10', to='api.playerdota2'),
        ),
        migrations.AddField(
            model_name='gamedota2',
            name='player_2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='player_2', to='api.playerdota2'),
        ),
        migrations.AddField(
            model_name='gamedota2',
            name='player_3',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='player_3', to='api.playerdota2'),
        ),
        migrations.AddField(
            model_name='gamedota2',
            name='player_4',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='player_4', to='api.playerdota2'),
        ),
        migrations.AddField(
            model_name='gamedota2',
            name='player_5',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='player_5', to='api.playerdota2'),
        ),
        migrations.AddField(
            model_name='gamedota2',
            name='player_6',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='player_6', to='api.playerdota2'),
        ),
        migrations.AddField(
            model_name='gamedota2',
            name='player_7',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='player_7', to='api.playerdota2'),
        ),
        migrations.AddField(
            model_name='gamedota2',
            name='player_8',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='player_8', to='api.playerdota2'),
        ),
        migrations.AddField(
            model_name='gamedota2',
            name='player_9',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='player_9', to='api.playerdota2'),
        ),
        migrations.CreateModel(
            name='PlayerGameStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold', models.IntegerField()),
                ('kills', models.IntegerField()),
                ('dead', models.IntegerField()),
                ('assists', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.gamedota2')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.playerdota2')),
            ],
        ),
    ]
