# Generated by Django 4.2.5 on 2023-11-23 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_gamedota2_player_gamedota2_player_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamedota2',
            name='player',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.playerdota2'),
        ),
    ]
