# Generated by Django 4.2.5 on 2023-11-23 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_gamedota2_player'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamedota2',
            old_name='role',
            new_name='title',
        ),
    ]
