# Generated by Django 4.2.5 on 2023-11-25 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_gamedota2_assists_remove_gamedota2_dead_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamedota2',
            name='characters',
        ),
        migrations.RemoveField(
            model_name='gamedota2',
            name='hero_played',
        ),
        migrations.RemoveField(
            model_name='gamedota2',
            name='player',
        ),
        migrations.RemoveField(
            model_name='gamedota2',
            name='player_1',
        ),
        migrations.RemoveField(
            model_name='gamedota2',
            name='player_10',
        ),
        migrations.RemoveField(
            model_name='gamedota2',
            name='player_2',
        ),
        migrations.RemoveField(
            model_name='gamedota2',
            name='player_3',
        ),
        migrations.RemoveField(
            model_name='gamedota2',
            name='player_4',
        ),
        migrations.RemoveField(
            model_name='gamedota2',
            name='player_5',
        ),
        migrations.RemoveField(
            model_name='gamedota2',
            name='player_6',
        ),
        migrations.RemoveField(
            model_name='gamedota2',
            name='player_7',
        ),
        migrations.RemoveField(
            model_name='gamedota2',
            name='player_8',
        ),
        migrations.RemoveField(
            model_name='gamedota2',
            name='player_9',
        ),
        migrations.AddField(
            model_name='gamedota2',
            name='date',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='playergamestats',
            name='hero',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.dotaheroes'),
        ),
        migrations.DeleteModel(
            name='CharacterDota2',
        ),
    ]
