# Generated by Django 4.2.5 on 2023-11-25 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_gamedota2_characters_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamedota2',
            name='date',
            field=models.TimeField(),
        ),
    ]
