# Generated by Django 4.2.5 on 2023-11-25 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_gamedota2_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamedota2',
            name='date',
            field=models.DateField(),
        ),
    ]
